---
engines:
 csslint:
   enabled: true
 eslint:
   enabled: true   
languages:
  css:
    extensions:
      - _css.resource
  javascript:
    extensions:
      - _js.resource
exclude_paths:
  - src/documents/
  - src/classes/MetadataService.cls
  - src/classes/MetadataServiceTest.cls
  - src/classes/SObjectDataLoader.cls
  - src/classes/SObjectDataLoaderTest.cls
  - src/classes/SmartFactory.cls
  - src/classes/fflib_*.cls
  - src/classes/ToolingAPI.cls
  - src/classes/ToolingAPITest.cls
  - '*.schema'
  - '*.xml'
  - '*.actionLinkGroupTemplate'  
  - '*.snapshot' 
  - '*.component'
  - '*.page' 
  - '*.appMenu'
  - '*.approvalProcess'  
  - '*.assignmentRules'
  - '*.authprovider' 
  - '*.autoResponseRules'
  - '*.callCenter' 
  - '*.crt'
  - '*.channelLayout'  
  - '*.community'
  - '*.connectedApp' 
  - '*.corsWhitelistOrigin'
  - '*.app'  
  - '*.customApplicationComponent'
  - '*.feedFilter' 
  - '*.labels'
  - '*.md' 
  - '*.object'
  - '*.objectTranslation'  
  - '*.weblink'
  - '*.customPermission' 
  - '*.site'
  - '*.tab'  
  - '*.dashboard'
  - '*.datacategorygroup'  
  - '*.delegateGroup'
  - '*.email'  
  - '*.escalationRules'
  - '*.dataSource' 
  - '*.flexipage'
  - '*.flow' 
  - '*.flowDefinition'
  - '*.group'  
  - '*.homePageComponent'
  - '*.homePageLayout' 
  - '*.installedPackage'
  - '*.layout' 
  - '*.letter'
  - '*.matchingRule' 
  - '*.namedCredential'
  - '*.pathAssistant'  
  - '*.permissionset'
  - '*.cachePartition' 
  - '*.portal'
  - '*.postTemplate' 
  - '*.profile'
  - '*.queue'  
  - '*.quickAction'
  - '*.remoteSite' 
  - '*.report'
  - '*.reportType' 
  - '*.role'
  - '*.samlssoconfig'  
  - '*.scf'
  - '*.settings' 
  - '*.sharingRules'
  - '*.sharingSet'
  - '*.site' 
  - '*.synonymDictionary'
  - '*.transactionSecurityPolicy'  
  - '*.workflow'
  - '*.xorghub'
  - '*.globalPicklist'
  - '*.translation'
